ERROR - 2024-02-26 14:14:20 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci-framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci-framework\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci-framework\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#6 D:\xampp\htdocs\ci-framework\app\Controllers\login.php(51): CodeIgniter\BaseModel->first()
#7 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(941): App\Controllers\login->loginAuth()
#8 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#9 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci-framework\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci-framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci-framework\system\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci-framework\system\BaseModel.php(676): CodeIgniter\Model->doFirst()
#5 D:\xampp\htdocs\ci-framework\app\Controllers\login.php(51): CodeIgniter\BaseModel->first()
#6 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(941): App\Controllers\login->loginAuth()
#7 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
#8 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci-framework\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-26 14:14:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `user`
WHERE `email` = :email:
AND `role_id` = :role_id:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(270): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(676): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\login.php(51): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\login->loginAuth()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 14:15:04 --> CodeIgniter\Filters\Exceptions\FilterException: "authFilter" filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 352.
 1 SYSTEMPATH\Filters\Filters.php(352): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authFilter')
 2 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilter('authFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-02-26 14:15:36 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci-framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `user`.*...', Array, false)
#4 D:\xampp\htdocs\ci-framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci-framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\xampp\htdocs\ci-framework\app\Controllers\user.php(27): CodeIgniter\BaseModel->findAll()
#7 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(941): App\Controllers\user->index()
#8 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user))
#9 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci-framework\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in D:\xampp\htdocs\ci-framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci-framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci-framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `user`.*...', Array, false)
#3 D:\xampp\htdocs\ci-framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci-framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\xampp\htdocs\ci-framework\app\Controllers\user.php(27): CodeIgniter\BaseModel->findAll()
#6 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(941): App\Controllers\user->index()
#7 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user))
#8 D:\xampp\htdocs\ci-framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci-framework\public\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-02-26 14:15:36 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT `user`.*, `user_roles`.`role`
FROM `user`
LEFT JOIN `user_roles` ON `user_roles`.`id` = `user`.`role_id`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\user.php(27): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\user->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\user))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 14:16:21 --> CodeIgniter\Filters\Exceptions\FilterException: "authFilter" filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 352.
 1 SYSTEMPATH\Filters\Filters.php(352): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authFilter')
 2 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilter('authFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 14:16:30 --> Error: Class "Firebase\JWT\JWT" not found
in APPPATH\Controllers\login.php on line 73.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\login->loginAuth()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 14:16:54 --> CodeIgniter\Filters\Exceptions\FilterException: "authFilter" filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 352.
 1 SYSTEMPATH\Filters\Filters.php(352): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authFilter')
 2 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilter('authFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 14:18:31 --> Error: Class "Firebase\JWT\JWT" not found
in APPPATH\Controllers\login.php on line 75.
 1 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\login->loginAuth()
 2 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\login))
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-02-26 16:57:37 --> CodeIgniter\Filters\Exceptions\FilterException: "authFilter" filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 352.
 1 SYSTEMPATH\Filters\Filters.php(352): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('authFilter')
 2 SYSTEMPATH\CodeIgniter.php(467): CodeIgniter\Filters\Filters->enableFilter('authFilter', 'before')
 3 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
