ERROR - 2024-06-24 13:07:29 --> mysqli_sql_exception: Unknown column 'table_name' in 'field list' in /var/www/eazyhosting.in/public_html/api/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /var/www/eazyhosting.in/public_html/api/system/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 /var/www/eazyhosting.in/public_html/api/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 /var/www/eazyhosting.in/public_html/api/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 /var/www/eazyhosting.in/public_html/api/system/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 /var/www/eazyhosting.in/public_html/api/system/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/eazyhosting.in/public_html/api/system/BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 /var/www/eazyhosting.in/public_html/api/system/Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 /var/www/eazyhosting.in/public_html/api/system/BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 /var/www/eazyhosting.in/public_html/api/app/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save(Array)
#9 /var/www/eazyhosting.in/public_html/api/app/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state w...', 'state')
#10 /var/www/eazyhosting.in/public_html/api/app/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', Array)
#11 /var/www/eazyhosting.in/public_html/api/app/Controllers/State.php(115): App\Models\BaseModel->update('38', Array)
#12 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(941): App\Controllers\State->update('38')
#13 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
#14 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 /var/www/eazyhosting.in/public_html/api/public/index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-06-24 13:07:29 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 2 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
 7 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
 8 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
 9 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
10 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
11 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
12 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-06-24 13:07:29 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 311.
 1 SYSTEMPATH/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:29\')')
 2 SYSTEMPATH/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:29\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 4 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
 9 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
10 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
11 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
12 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
13 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
14 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-06-24 13:07:29 --> [Caused by] mysqli_sql_exception: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 306.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:29\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:29\')')
 3 SYSTEMPATH/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:29\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 5 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
10 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
11 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
12 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
13 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
14 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
15 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
16 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2024-06-24 13:07:47 --> mysqli_sql_exception: Unknown column 'table_name' in 'field list' in /var/www/eazyhosting.in/public_html/api/system/Database/MySQLi/Connection.php:306
Stack trace:
#0 /var/www/eazyhosting.in/public_html/api/system/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `ac...', 0)
#1 /var/www/eazyhosting.in/public_html/api/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ac...')
#2 /var/www/eazyhosting.in/public_html/api/system/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ac...')
#3 /var/www/eazyhosting.in/public_html/api/system/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ac...', Array, false)
#4 /var/www/eazyhosting.in/public_html/api/system/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
#5 /var/www/eazyhosting.in/public_html/api/system/BaseModel.php(802): CodeIgniter\Model->doInsert(Array)
#6 /var/www/eazyhosting.in/public_html/api/system/Model.php(744): CodeIgniter\BaseModel->insert(Array, false)
#7 /var/www/eazyhosting.in/public_html/api/system/BaseModel.php(713): CodeIgniter\Model->insert(Array, false)
#8 /var/www/eazyhosting.in/public_html/api/app/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save(Array)
#9 /var/www/eazyhosting.in/public_html/api/app/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state w...', 'state')
#10 /var/www/eazyhosting.in/public_html/api/app/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', Array)
#11 /var/www/eazyhosting.in/public_html/api/app/Controllers/State.php(115): App\Models\BaseModel->update('38', Array)
#12 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(941): App\Controllers\State->update('38')
#13 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
#14 /var/www/eazyhosting.in/public_html/api/system/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#15 /var/www/eazyhosting.in/public_html/api/public/index.php(79): CodeIgniter\CodeIgniter->run()
#16 {main}
CRITICAL - 2024-06-24 13:07:47 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/BaseConnection.php on line 647.
 1 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 2 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 6 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
 7 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
 8 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
 9 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
10 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
11 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
12 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-06-24 13:07:47 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 311.
 1 SYSTEMPATH/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:47\')')
 2 SYSTEMPATH/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:47\')')
 3 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 4 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 8 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
 9 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
10 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
11 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
12 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
13 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
14 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
15 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-06-24 13:07:47 --> [Caused by] mysqli_sql_exception: Unknown column 'table_name' in 'field list'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 306.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(306): mysqli->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:47\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:47\')')
 3 SYSTEMPATH/Database/BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (\'3\', \'update\', \'Updated state with data: {\\"name\\":\\"Test1\\",\\"updated_by\\":\\"3\\",\\"status\\":\\"1\\"}\', \'state\', \'2024-06-24 13:07:47\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `activity_logs` (`user_id`, `action`, `description`, `table_name`, `created_at`) VALUES (:user_id:, :action:, :description:, :table_name:, :created_at:)', [...], false)
 5 SYSTEMPATH/Model.php(326): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(802): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(744): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(713): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Services/ActivityLogger.php(26): CodeIgniter\BaseModel->save([...])
10 APPPATH/Services/ActivityLogger.php(37): App\Services\ActivityLogger->log('3', 'update', 'Updated state with data: {"name":"Test1","updated_by":"3","status":"1"}', 'state')
11 APPPATH/Models/BaseModel.php(36): App\Services\ActivityLogger->logUpdate('3', 'state', [...])
12 APPPATH/Controllers/State.php(115): App\Models\BaseModel->update('38', [...])
13 SYSTEMPATH/CodeIgniter.php(941): App\Controllers\State->update('38')
14 SYSTEMPATH/CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\State))
15 SYSTEMPATH/CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
16 FCPATH/index.php(79): CodeIgniter\CodeIgniter->run()
